name: Build all on PR

on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Chain
        id: build-chain
        uses: kiegroup/github-action-build-chain@v3.5.6
        with:
          definition-file: ./ci/dependency-tree.yml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: check package.json
        run: |
          echo "Checking package.json"
          cat package.json
