name: Update Issue Status
on:
  workflow_dispatch:
jobs:
  update_issue_status:
    uses: flowfuse/.github/.github/workflows/record-in-review.yml@main
    secrets:
      PROJECT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
